# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Company.create(symbol: "AAPL")
Company.create(symbol: "GOOG")
Company.create(symbol: "MSFT")
Company.create(symbol: "FB")
Company.create(symbol: "INTC")
Company.create(symbol: "IBM")
Company.create(symbol: "ORCL")
Company.create(symbol: "TSM")
Company.create(symbol: "CSCO")
Company.create(symbol: "SAP")
Company.create(symbol: "DCM")
Company.create(symbol: "AVGO")
Company.create(symbol: "QCOM")
Company.create(symbol: "TXN")
Company.create(symbol: "NVDA")
Company.create(symbol: "ADBE")
Company.create(symbol: "CRM")
Company.create(symbol: "BIDU")
Company.create(symbol: "ADP")
Company.create(symbol: "ITW")
Company.create(symbol: "YHOO")
Company.create(symbol: "AMAT")
Company.create(symbol: "HPE")
Company.create(symbol: "VMW")
Company.create(symbol: "NXPI")
Company.create(symbol: "CTSH")
Company.create(symbol: "ETN")
Company.create(symbol: "INFY")
Company.create(symbol: "INTU")
Company.create(symbol: "ATVI")
Company.create(symbol: "MU")
Company.create(symbol: "NOK")
Company.create(symbol: "HPQ")
Company.create(symbol: "EA")
Company.create(symbol: "ADI")
Company.create(symbol: "FISV")
Company.create(symbol: "WIT")
Company.create(symbol: "OMC")
Company.create(symbol: "KYO")
Company.create(symbol: "LRCX")
Company.create(symbol: "ADSK")
Company.create(symbol: "ADSK")
Company.create(symbol: "INFO")
